FROM golang:1

ENV PROJECT=notifications-push
ENV REPO_PATH="github.com/Financial-Times/${PROJECT}"


ARG GITHUB_USERNAME
ARG GITHUB_TOKEN

WORKDIR /${PROJECT}

RUN git config --global url."https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com".insteadOf "https://github.com" \
  && go env -w GOPRIVATE=github.com/Financial-Times

RUN git clone https://github.com/vishnubob/wait-for-it.git \
  && cd wait-for-it \
  && mv ./wait-for-it.sh /${PROJECT}

COPY go.mod /
COPY go.sum /
RUN go mod download

COPY . /${PROJECT}/

ENTRYPOINT ["./wait-for-it.sh", "opa:8181", "-t", "60", "--"]
