version: '3.8'
services:
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.tests
      args:
        GITHUB_USERNAME: "${GITHUB_USERNAME}"
        GITHUB_TOKEN: "${GITHUB_TOKEN}"
    container_name: test-runner
    depends_on:
      - kafka
    environment:
      - ALLOWED_ALL_CONTENT_TYPE="Article,ContentPackage,Audio"
      - API_BASE_URL="http://api-t.ft.com"
      - API_URL_RESOURCE=content
      - CONTENT_TYPE_ALLOWLIST="application/vnd.ft-upp-article+json,application/vnd.ft-upp-audio+json,application/vnd.ft-upp-live-blog-post-internal+json,application/vnd.ft-upp-live-blog-package-internal+json"
      - CONTENT_URI_ALLOWLIST="^http://(content|upp)(-collection|-content-placeholder|-notifications-creator)?(-mapper|-unfolder)?(-pr|-iw)?(-uk-.*)?\\.svc\\.ft\\.com(:\\d{2,5})?/(content|complementarycontent)/[\\w-]+.*\$"
      - DEFAULT_SUBSCRIPTION_TYPE="Article"
      - GROUP_ID=notifications-push-integration-tests
      - KAFKA_ADDRESS=kafka:19092
      - KAFKA_LAG_TOLERANCE=120
      - NOTIFICATIONS_DELAY=10
      - NOTIFICATIONS_RESOURCE=content
      - OPA_FILE_LOCATION="./opa_modules/special_content.rego"
      - SUPPORTED_SUBSCRIPTION_TYPE="Article,ContentRelation,ContentPackage,Audio,All,LiveBlogPackage,LiveBlogPost,Content"
      - TOPIC=PostPublicationEvents
    command: go test -mod=readonly -v -race -tags=integration ./...
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - '19092:19092'
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://kafka:19092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000