version: '3'
services:
  test-runner:
    container_name: test-runner
    build:
      context: .
      dockerfile: Dockerfile.tests
      args:
        GITHUB_USERNAME: "${GITHUB_USERNAME}"
        GITHUB_TOKEN: "${GITHUB_TOKEN}"
    environment:
      OPA_URL: "http://opa:8181"
      CGO_ENABLED: 1
      KAFKA_ADDRESS: kafka:9092
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      API_BASE_URL: "http://api-t.ft.com"
      GROUP_ID: "notifications-push-test1"
      TOPIC: "PostPublicationEvents"
      NOTIFICATIONS_DELAY: 10
      NOTIFICATIONS_RESOURCE: "content"
      API_URL_RESOURCE: "content"
      CONTENT_URI_ALLOWLIST: "^http://(content|upp)(-collection|-content-placeholder|-notifications-creator)?(-mapper|-unfolder)?(-pr|-iw)?(-uk-.*)?\\.svc\\.ft\\.com(:\\d{2,5})?/(content|complementarycontent)/[\\w-]+.*$"
      CONTENT_TYPE_ALLOWLIST: "application/vnd.ft-upp-article+json,application/vnd.ft-upp-audio+json,application/vnd.ft-upp-live-blog-post+json,application/vnd.ft-upp-live-blog-package+json"
      ALLOWED_ALL_CONTENT_TYPE: "Article,ContentPackage,Audio"
      SUPPORTED_SUBSCRIPTION_TYPE: "Annotations,Article,ContentPackage,Audio,All,LiveBlogPackage,LiveBlogPost,Content"
      DEFAULT_SUBSCRIPTION_TYPE: "Article"
      APP_PORT: 8080
    ports:
      - 8000:8080
    command: ["go", "test", "-mod=readonly", "-v", "-race", "-tags=integration", "./..."]
    depends_on:
      - opa
  opa:
    image: coco/cm-open-policy-agent:latest
    environment:
      GITHUB_USERNAME: "${GITHUB_USERNAME}"
      GITHUB_TOKEN: "${GITHUB_TOKEN}"
      OPA_VERSION: 0.67.0
      OPA_BUNDLE_PROJECT: "notifications-push"
    container_name: opa-container
    ports:
      - 8181:8181