# Default values for notifications-push.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
replicaCount: 2
image:
  repository: coco/notifications-push
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: 100Mi
  limits:
    memory: 512Mi
env:
  GROUP_ID: ""
  TOPIC: ""
  CONSUMER_BACKOFF: ""
  NOTIFICATIONS_RESOURCE: ""
  WHITELIST:  ""
  PUSH_PORT: ""
