# Default values for notifications-push.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
  isResilient: "false"
  serviceAccountName: eksctl-notifications-push-serviceaccount
replicaCount: 2
image:
  repository: coco/notifications-push
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: 100Mi
  limits:
    memory: 512Mi
env:
  GROUP_ID: ""
  TOPIC: ""
  NOTIFICATIONS_RESOURCE: ""
  API_URL_RESOURCE: ""
  MONITOR_NOTIFICATIONS: "true"
  INCLUDE_SCOOP: "false"
  PUSH_PORT: ""
  UPDATE_EVENT_TYPE: "http://www.ft.com/thing/ThingChangeType/UPDATE"
  OPA_URL: "http://localhost:8181"
  NOTIFICATIONS_PUSH_POLICY_PATH: "notifications_push/special_content"
openPolicyAgentSidecar:
  name: open-policy-agent
  repository: openpolicyagent/opa
  tag: 0.67.0
  pullPolicy: IfNotPresent