version: 2.1

orbs:
  ft-golang-ci: financial-times/golang-ci@1

executors:
  default-with-kafka:
    docker:
      - image: golang:1
        environment:
          GOPATH: /go
          KAFKA_BOOTSTRAP_SERVERS: localhost:9092
      - image: confluentinc/cp-zookeeper:7.2.1
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181
      - image: confluentinc/cp-kafka:7.2.1
        environment:
          KAFKA_BROKER_ID: 1
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
          KAFKA_ZOOKEEPER_CONNECT: localhost:2181
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

workflows:
  tests_and_docker:
    jobs:
      - ft-golang-ci/build-and-test:
          name: build-and-test-project
          executor-name:
            name: default-with-kafka
          context: cm-team-github
      - ft-golang-ci/docker-build:
          name: build-docker-image
          requires:
            - build-and-test-project
          context: cm-team-github
  snyk-scanning:
    jobs:
      - ft-golang-ci/scan:
          name: scan-dependencies
          context:
            - cm-team-snyk
            - cm-team-github
