# Values used for the deployed application.
replicaCount: 2
service:
  name: list-notifications-push
env:
  TOPIC: "PublicationNotificationEvents"
  NOTIFICATIONS_RESOURCE: "lists"
  API_URL_RESOURCE: "lists"
  CONTENT_TYPE_ALLOWLIST: "application/vnd.ft-upp-list+json"
  API_KEY_VALIDATION_ENDPOINT: "push-api-internal/t800/a"
  OPA_FILE_LOCATION: "./opa_modules/central_banking.rego"

  # We don't want to match any content URIs for this deployment.
  CONTENT_URI_ALLOWLIST: "$."
  PUSH_PORT: "8599"
  DEFAULT_SUBSCRIPTION_TYPE: "List"
