# Values used for the deployed application.
replicaCount: 2
service:
  name: notifications-push
env:
  TOPIC: "PublicationNotificationEvents"
  METADATA_TOPIC: "PostConceptAnnotations"
  CONSUMER_BACKOFF: "2"
  NOTIFICATIONS_RESOURCE: "content"
  CONTENT_URI_WHITELIST: "^http://(methode|wordpress-article|content|upp)(-collection|-content-placeholder|-notifications-creator)?(-mapper|-unfolder|)(-pr|-iw)?(-uk-.*)?\\.svc\\.ft\\.com(:\\d{2,5})?/(content|complementarycontent)/[\\w-]+.*$"
  CONTENT_TYPE_WHITELIST: "application/vnd.ft-upp-article-internal+json,application/vnd.ft-upp-content-package+json,application/vnd.ft-upp-audio+json,application/vnd.ft-upp-live-blog-post-internal+json,application/vnd.ft-upp-live-blog-package-internal+json"
  WHITELISTED_METADATA_ORIGIN_SYSTEM_HEADERS: "http://cmdb.ft.com/systems/pac, http://cmdb.ft.com/systems/methode-web-pub, http://cmdb.ft.com/systems/next-video-editor"
  API_KEY_VALIDATION_ENDPOINT: "t800/a"
  API_KEY_POLICIES_ENDPOINT: "t800/policy"
  ALLOWED_ALL_CONTENT_TYPE: "Article,ContentPackage,Audio,Content"
  SUPPORTED_SUBSCRIPTION_TYPE: "Annotations,Article,ContentPackage,Audio,All,LiveBlogPackage,LiveBlogPost,Content"
  PUSH_PORT: "8599"
  E2E_TEST_IDS: "427f2a19-2ae7-47c1-b580-c225fa0a0199"
  DEFAULT_SUBSCRIPTION_TYPE: "Article"
