# Values used for the deployed application.
replicaCount: 2
service:
  name: notifications-push
env:
  TOPIC: "PublicationNotificationEvents"
  NOTIFICATIONS_RESOURCE: "content"
  API_URL_RESOURCE: "content"
  CONTENT_URI_ALLOWLIST: "^http://(content|upp)(-collection|-content-placeholder|-notifications-creator)?(-mapper|-unfolder)?(-pr|-iw)?(-uk-.*)?\\.svc\\.ft\\.com(:\\d{2,5})?/(content|complementarycontent)/[\\w-]+.*$"
  CONTENT_TYPE_ALLOWLIST: "application/vnd.ft-upp-article-internal+json,application/vnd.ft-upp-audio+json,application/vnd.ft-upp-live-blog-post-internal+json,application/vnd.ft-upp-live-blog-package-internal+json,application/vnd.ft-upp-content-placeholder-internal+json"

  API_KEY_VALIDATION_ENDPOINT: "t800/a"
  API_KEY_POLICIES_ENDPOINT: "t800/policy"

  ALLOWED_ALL_CONTENT_TYPE: "Article,ContentPackage,Audio,Content"
  SUPPORTED_SUBSCRIPTION_TYPE: "Article,ContentPackage,Audio,All,LiveBlogPackage,LiveBlogPost,Content"
  DEFAULT_SUBSCRIPTION_TYPE: "Article"
  INCLUDE_SCOOP: "true"

  E2E_TEST_IDS: "427f2a19-2ae7-47c1-b580-c225fa0a0199"
  PUSH_PORT: "8599"

  OPA_FILE_LOCATION: "./opa_modules/central_banking.rego"
