# Values used for the deployed application.
replicaCount: 2
service:
  name: notifications-push
env:
  TOPIC: "PostPublicationEvents"
  CONSUMER_BACKOFF: "2"
  NOTIFICATIONS_RESOURCE: "content"
  WHITELIST: "^http://(methode|wordpress|content)-(article|collection|content-placeholder)-(mapper|unfolder)(-pr|-iw)?(-uk-.*)?\\.svc\\.ft\\.com(:\\d{2,5})?/(content|complementarycontent)/[\\w-]+.*$"
  PUSH_PORT: "8599"
