# Values used for the deployed application.
replicaCount: 2
service:
  name: page-notifications-push
env:
  TOPIC: "PublicationNotificationEvents"
  NOTIFICATIONS_RESOURCE: "pages"
  API_URL_RESOURCE: "pages"
  CONTENT_TYPE_ALLOWLIST: "application/vnd.ft-upp-page+json"
  API_KEY_VALIDATION_ENDPOINT: "push-api-internal/t800/a"

  # We don't want to match any content URIs for this deployment.
  CONTENT_URI_ALLOWLIST: "$."
  PUSH_PORT: "8599"

  DEFAULT_SUBSCRIPTION_TYPE: "Page"
